config/routes.rb
Rails.application.routes.draw do
  post 'device_versions', to: "device_versions#create" , as: "device_version"
  delete 'device_versions/:id', to: "device_versions#destroy", as: "delete_device_version"
  resources :versions
  resources :programs
  resources :issues
  resources :devices
  resources :targets
  resources :esps
  root to: "devices#index"
  devise_for :users, :skip => :registration


  get "/esps/:mac/version", to: "esps#version" , as: "checkVersion"
  get "/esps/:mac/:page/:size", to: "esps#sendData" , as: "sendData"
  get "/esps/:mac/updated", to: "esps#updated" , as: "updated"
  post "/esps/:mac/error/:message", to: "esps#error" , as: "error"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/target.rb
class Target < ApplicationRecord
    has_and_belongs_to_many :programs
    has_many :devices
    validates :name, presence: true
    validates :name, uniqueness: true

    def to_s
        return self.name
    end

end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_target, only: [:show, :edit, :update, :destroy]

  # GET /targets
  # GET /targets.json
  def index
    @targets = Target.all
  end

  # GET /targets/1
  # GET /targets/1.json
  def show
  end

  # GET /targets/new
  def new
    @target = Target.new
  end

  # GET /targets/1/edit
  def edit
  end

  # POST /targets
  # POST /targets.json
  def create
    redirect_to targets_path, alert: "Solo se permite atmega328p"
    return
    @target = Target.new(target_params)

    respond_to do |format|
      if @target.save
        format.html { redirect_to @target, notice: 'Target was successfully created.' }
        format.json { render :show, status: :created, location: @target }
      else
        format.html { render :new }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /targets/1
  # PATCH/PUT /targets/1.json
  def update
    respond_to do |format|
      if @target.update(target_params)
        format.html { redirect_to @target, notice: 'Target was successfully updated.' }
        format.json { render :show, status: :ok, location: @target }
      else
        format.html { render :edit }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1
  # DELETE /targets/1.json
  def destroy
    @target.destroy
    respond_to do |format|
      format.html { redirect_to targets_url, notice: 'Target was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_target
      @target = Target.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def target_params
      params.require(:target).permit(:name)
    end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/_form.html.erb
<%= form_with(model: target, local: true) do |form| %>
  <% if target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(target.errors.count, "error") %> prohibited this target from being saved:</h2>

      <ul>
      <% target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-sm-3">
      <%= form.label :name %>
      <%= form.text_field :name, id: :target_name , class:"form-control"%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit  class:"btn btn-success" %>
  </div>
<% end %>

app/views/targets/edit.html.erb
<h1>Editing Target</h1>

<%= render 'form', target: @target %>

<%= link_to 'Show', @target,class:"btn btn-primary" %> |
<%= link_to 'Cancel', targets_path,class:"btn btn-danger" %>

app/views/targets/index.html.erb
<h1>Targets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @targets.each do |target| %>
      <tr>
        <td><%= target.name %></td>
        <td><%= link_to 'Show', target, class:"btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_target_path(target), class:"btn btn-warning" %></td>
        <td><%= link_to 'Destroy', target, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Target', new_target_path, class:"btn btn-success" %>

app/views/targets/new.html.erb
<h1>New Target</h1>

<%= render 'form', target: @target %>

<%= link_to 'Cancel', targets_path,class:"btn btn-danger" %>

app/views/targets/show.html.erb
<div class="panel panel-primary">
    <div class="panel-heading">Program Infomation</div>
    <div class="panel-body">
      <div class="row">
        <div class="col-sm-3">
          <p>
            <strong>Name:</strong>
            <%= @target.name %>
          </p>
        </div>
      </div>
      <div class="row">
          <table class="table">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
            
              <tbody>
                <% @target.programs.each do |program| %>
                  <tr>
                    <td><%= program.name %></td>
                    <td><%= program.description %></td>
                    <td><%= link_to 'Show', program, class:"btn btn-primary" %></td>
                    <td><%= link_to 'Edit', edit_program_path(program), class:"btn btn-warning" %></td>
                    <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
  
      </div>
      <%= link_to 'Edit', edit_target_path(@target), class:"btn btn-warning" %> |
      <%= link_to 'Back', targets_path , class:"btn btn-success" %> 
    </div>    
  </div>