config/routes.rb
Rails.application.routes.draw do
  post 'device_versions', to: "device_versions#create" , as: "device_version"
  delete 'device_versions/:id', to: "device_versions#destroy", as: "delete_device_version"
  resources :versions
  resources :programs
  resources :issues
  resources :devices
  resources :targets
  resources :esps
  root to: "devices#index"
  devise_for :users, :skip => :registration


  get "/esps/:mac/version", to: "esps#version" , as: "checkVersion"
  get "/esps/:mac/:page/:size", to: "esps#sendData" , as: "sendData"
  get "/esps/:mac/updated", to: "esps#updated" , as: "updated"
  post "/esps/:mac/error/:message", to: "esps#error" , as: "error"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :device , optional: true
  validates :message, presence: true
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:message, :device_id)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_with(model: issue, local: true) do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :message %>
    <%= form.text_field :message, id: :issue_message, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :device_id %>
    <%= form.select :device_id,  content_tag(:option,'Seleccione...',:value=>"") + options_from_collection_for_select(Device.all, "id", :to_s,:selected => form.object.device_id),{}, {:class => 'form-control'} %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Show', @issue , class:"btn btn-primary"%> |
<%= link_to 'Cancel', issues_path , class:"btn btn-danger"%>

app/views/issues/index.html.erb
<h1>Issues</h1>

<table class="table">
  <thead>
    <tr>
      <th>Message</th>
      <th>Device</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.message %></td>
        <td><%= issue.device %></td>
        <td><%= link_to 'Show', issue, class:"btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue), class:"btn btn-warning" %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path, class:"btn btn-success" %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Cancel', issues_path, class:"btn btn-danger" %>

app/views/issues/show.html.erb
<p>
  <strong>Message:</strong>
  <%= @issue.message %>
</p>

<p>
  <strong>Device:</strong>
  <%if !@issue.device.nil? %>
    <%= link_to @issue.device,@issue.device %>
  <% end %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue), class:"btn btn-warning" %> |
<%= link_to 'Back', issues_path, class:"btn btn-success" %>