config/routes.rb
Rails.application.routes.draw do
  post 'device_versions', to: "device_versions#create" , as: "device_version"
  delete 'device_versions/:id', to: "device_versions#destroy", as: "delete_device_version"
  resources :versions
  resources :programs
  resources :issues
  resources :devices
  resources :targets
  resources :esps
  root to: "devices#index"
  devise_for :users, :skip => :registration


  get "/esps/:mac/version", to: "esps#version" , as: "checkVersion"
  get "/esps/:mac/:page/:size", to: "esps#sendData" , as: "sendData"
  get "/esps/:mac/updated", to: "esps#updated" , as: "updated"
  post "/esps/:mac/error/:message", to: "esps#error" , as: "error"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/program.rb
class Program < ApplicationRecord
    has_and_belongs_to_many :targets
    has_many :versions
    validates :name, presence: true
    validates :name, uniqueness: true

    def to_s
        return name
    end

    def lastVersion
        return self.versions.last
    end
    def devices
        return Device.where(id:self.versions.joins(:device_versions).select("device_versions.device_id as id").distinct.map{|d| d.id})
    end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:name, :description, target_ids: [])
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_with(model: program, local: true) do |form| %>
  <% if program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="form-group col-sm-4">
      <%= form.label :name %>
      <%= form.text_field :name, id: :program_name, class:"form-control" %>
    </div>    
  </div>
  <div class="row">
    <div class="form-group col-sm-4">
      <%= form.label :description %>
      <%= form.text_field :description, id: :program_description, class:"form-control" %>
    </div>
  </div>
  <%=form.collection_select :target_ids,Target.all,:id,:name,{}, {multiple: true, :class => 'selectpicker form-control', :id => "temas"}%>

  <div class="actions">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>
<script type="text/javascript">
  $('#temas').selectpicker('hide');
  $('#temas').selectpicker('show');
  $('#temas').selectpicker('refresh'); 
</script>

app/views/programs/edit.html.erb
<h1>Editing Program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Show', @program , class:"btn btn-primary"%> |
<%= link_to 'Back', programs_path , class:"btn btn-danger"%>

app/views/programs/index.html.erb
<h1>Programs</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= program.name %></td>
        <td><%= program.description %></td>
        <td><%= link_to 'Show', program, class:"btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_program_path(program), class:"btn btn-warning" %></td>
        <td><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Program', new_program_path, class:"btn btn-success" %>

app/views/programs/new.html.erb
<h1>New Program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Cancel', programs_path , class:"btn btn-danger"%>

app/views/programs/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">Program Infomation</div>
  <div class="panel-body">
    <div class="row">
      <div class="col-sm-3">
        <p>
          <strong>Name:</strong>
          <%= @program.name %>
        </p>
      </div>
      <div class="col-sm-6">
        <p>
          <strong>Description:</strong>
          <%= @program.description %>
        </p>
      </div>      
    </div>
    <div class="row">
      <div class="col-sm-12">
        <p>
          <strong>Compatible Targets:</strong>
          <% @program.targets.map{|t| "#{t.name}, "}.each do |target| %>
          <%= target %>
          <% end %>
        </p>
      </div>
    </div>
    <div class="row">
      <table class="table">
          <thead>
              <tr>
                <th>Name</th>
                <th>Latitude</th>
                <th>Longitude</th>
                <th>Target</th>
                <th>Esp</th>
                <th>Program</th>
                <th colspan="3"></th>
              </tr>
            </thead>
          
            <tbody>
              <% @program.devices.each do |device| %>
                <tr>
                  <td><%= device.name %></td>
                  <td><%= device.latitude %></td>
                  <td><%= device.longitude %></td>
                  <td><%= device.target %></td>
                  <td><%= device.esp %></td>
                  <td><%= device.program %></td>
                  <td><%= link_to 'Show', device , class: "btn btn-primary"%></td>
                  <td><%= link_to 'Edit', edit_device_path(device), class: "btn btn-warning" %></td>
                  <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
                </tr>
              <% end %>
            </tbody>
      </table>

    </div>
    <%= link_to 'Edit', edit_program_path(@program), class:"btn btn-warning" %> |
    <%= link_to 'Back', programs_path, class:"btn btn-success" %>
  </div>    
</div>