config/routes.rb
Rails.application.routes.draw do
  post 'device_versions', to: "device_versions#create" , as: "device_version"
  delete 'device_versions/:id', to: "device_versions#destroy", as: "delete_device_version"
  resources :versions
  resources :programs
  resources :issues
  resources :devices
  resources :targets
  resources :esps
  root to: "devices#index"
  devise_for :users, :skip => :registration


  get "/esps/:mac/version", to: "esps#version" , as: "checkVersion"
  get "/esps/:mac/:page/:size", to: "esps#sendData" , as: "sendData"
  get "/esps/:mac/updated", to: "esps#updated" , as: "updated"
  post "/esps/:mac/error/:message", to: "esps#error" , as: "error"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoRTdp2</title>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'bootstrap-select', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-default navbar-static-top" role="navigation" >
          <!-- El logotipo y el icono que despliega el menú se agrupan
          para mostrarlos mejor en los dispositivos móviles -->
          <div class="navbar-header navbar-brand" >
              <%= image_tag( 'logo.png' , size: '55x50')%>
          </div>
    
          <!-- Agrupar los enlaces de navegación, los formularios y cualquier
          otro elemento que se pueda ocultar al minimizar la barra -->
          <div class="collapse navbar-collapse navbar-ex1-collapse fixed-top bar-color">
            <ul class="nav navbar-nav mr-auto">
              <li class="nav-item dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Device <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="dropdown-item"><%= link_to "New", new_device_path %></li>
                  <li class="dropdown-item"><%= link_to "Index", devices_path %></li>
                  <li class="divider dropdown-item"></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">ESP<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="dropdown-item"><%= link_to "New" , new_esp_path %></li>
                  <li class="dropdown-item"><%= link_to "Index", esps_path %></li>
                  <li class="divider dropdown-item"></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Program<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="dropdown-item"><%= link_to "New" , new_program_path %></li>
                  <li class="dropdown-item"><%= link_to "Index", programs_path %></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Target <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li class="dropdown-item"><%= link_to "New", new_target_path %></li>
                  <li class="dropdown-item"><%= link_to "Index", targets_path %></li>
                  <li class="divider dropdown-item"></li>    
                </ul>
              </li>
              <li class="nav-item dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Issue<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li class="dropdown-item"><%= link_to "New" , new_issue_path %></li>
                    <li class="dropdown-item"><%= link_to "Index", issues_path %></li>
                  </ul>
              </li>
            </ul>
            <% if user_signed_in? %>
              <div class="nav navbar navbar-text" style="border: 0px solid #D2D2D2; margin: 0px; padding: 0px; padding-top: 5px;">
                <p style="text-align: center;">  Current User:  <br>
                <%= link_to current_user.email, "#"%> </p>
                </div>
            <% end %>				
            <ul class="nav navbar-nav navbar-right" style="padding-right: 10px">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"> </a>
                <ul class="dropdown-menu">
                  <% if user_signed_in? %>
                    <li><%= link_to "Log out", destroy_user_session_path,method: :delete %></li>
                  <% else %>    
                    <li><%= link_to "Sign in", new_session_path(resource_name)%></li>
                  <% end %>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
        <%if notice%>
        <p class="alert alert-info" role="alert"><%= notice %></p>
        <%end%>
        <%if alert %>
        <p class="alert alert-danger" role="alert"><%= alert %></p>
        <%end%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>